controllers:
    resource: ../src/Controller/
    type: attribute

profile_edit:
    path: /profile/edit
    controller: App\Controller\ProfileController::edit

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
